on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release and Docker Image

jobs:
  tagged-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Zurich"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            target/app.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          # By my personal convention same owner and project name in each system (GitHub and Docker Hub)
          tags: ${{ github.repository }}:latest,${{ github.repository }}:${{  github.ref_name }}
